# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'music' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for music
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'musicTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'music-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for music-tvOS

  target 'music-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
